server.port=8089
server.servlet.context-path=/common-utility

jira.baseUrl=https://nagachary018.atlassian.net
jira.email=${EMAIL}
jira.apiToken=${JIRA_API_TOKEN}
jira.projectSpaceKey=${JIRA_SPACE_KEY}
jira.storyPointsField=${JIRA_STORY_POINTS_FIELD:customfield_10016}


