#Application Properties
spring.application.name=requirement-analysis-agent
server.port=8081
server.servlet.context-path=/requirement-analysis-agent

#LLM Properties
spring.ai.ollama.base-url=http://localhost:11434
#spring.ai.ollama.chat.options.model=mistral
spring.ai.ollama.chat.options.model=qwen2.5
spring.ai.ollama.embedding.model=nomic-embed-text

#These are added after detecting that model is generating hallucinated response to avoid hallucination
spring.ai.ollama.chat.options.temperature=0.0
spring.ai.ollama.chat.options.top-p=0.1
spring.ai.ollama.chat.options.top-k=10
spring.ai.ollama.chat.options.repeat-penalty=1.3
spring.ai.ollama.chat.options.num-predict=2048
spring.ai.ollama.chat.options.seed=42

#Data Source Properties
spring.datasource.url=jdbc:postgresql://localhost:5432/vectordb
spring.datasource.username=${DB_USER:testuser}
spring.datasource.password=${DB_PASSWORD:testpwd}
spring.datasource.driver-class-name=org.postgresql.Driver

#Spring AI Vector DB Properties
spring.ai.vectorstore.pgvector.initialize-schema=true
spring.ai.vectorstore.pgvector.index-type=HNSW
spring.ai.vectorstore.pgvector.distance-type=COSINE_DISTANCE
spring.ai.vectorstore.pgvector.dimensions=768

#JIRA API Properties
jira.baseUrl=https://nagachary018.atlassian.net
jira.email=${JIRA_EMAIL}
jira.apiToken=${JIRA_API_TOKEN}
jira.projectSpaceKey=${JIRA_PROJECT_KEY}
jira.storyPointsField=customfield_10016

#Spring AI A2A Properties
spring.ai.a2a.server.enabled=true