#Application Properties
spring.application.name=requirement-analysis-agent
server.port=8081
server.servlet.context-path=/requirement-analysis-agent

#LLM Properties
spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.chat.options.model=mistral
spring.ai.ollama.embedding.model=nomic-embed-text

#Data Source Properties
spring.datasource.url=jdbc:postgresql://localhost:5432/vectordb
spring.datasource.username=${DB_USER:testuser}
spring.datasource.password=${DB_PASSWORD:testpwd}
spring.datasource.driver-class-name=org.postgresql.Driver

#Spring AI Vector DB Properties
spring.ai.vectorstore.pgvector.initialize-schema=true
spring.ai.vectorstore.pgvector.index-type=HNSW
spring.ai.vectorstore.pgvector.distance-type=COSINE_DISTANCE
spring.ai.vectorstore.pgvector.dimensions=768

#JIRA API Properties
jira.base-url=https://nagachary018.atlassian.net
jira.email=${JIRA_EMAIL}
jira.api-token=${JIRA_API_TOKEN}
jira.project-key=${JIRA_PROJECT_KEY}
jira.story-points-field=customfield_10016

#Spring AI A2A Properties
spring.ai.a2a.server.enabled=true