spring.application.name=orchestrator-agent
server.port=8080
server.servlet.context-path=/orchestrator-agent
agents.urls=http://localhost:8081
spring.main.lazy-initialization=true

# Ollama
spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.chat.options.model=qwen2.5
spring.ai.ollama.chat.options.temperature=0.0